version: "3.1"
services:
    www:
        image: tommygood/ncnu_im_mrbs:latest
        ports: 
            - "8081:80"
        volumes:
            - ./web:/var/www/html/
            - ./php/config.inc.php:/var/www/html/config.inc.php
        links:
            - db
        networks:
            - default
    db:
        image: mysql:8.0
        ports: 
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE} 
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        volumes:
            - ../tables.my.sql:/docker-entrypoint-initdb.d/010-tables.sql
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin
        links: 
            - db:db
        ports:
            - 8888:80
volumes:
    persistent:
